package xxfin.oracle.apps.ap.iou.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class iouHistVORowImpl extends OAViewRowImpl
{
  public static final int IOUID = 0;
  public static final int CREATEDBY = 1;
  public static final int CREATIONDATE = 2;
  public static final int UPDATEDBY = 3;
  public static final int LASTUPDATEDATE = 4;

  /**This is the default constructor (do not remove)
   */
  public iouHistVORowImpl()
  {
  }

  /**Gets the attribute value for the calculated attribute IouId
   */
  public Number getIouId()
  {
    return (Number) getAttributeInternal(IOUID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute IouId
   */
  public void setIouId(Number value)
  {
    setAttributeInternal(IOUID, value);
  }

  /**Gets the attribute value for the calculated attribute CreatedBy
   */
  public String getCreatedBy()
  {
    return (String) getAttributeInternal(CREATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
   */
  public void setCreatedBy(String value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**Gets the attribute value for the calculated attribute CreationDate
   */
  public Date getCreationDate()
  {
    return (Date) getAttributeInternal(CREATIONDATE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**Gets the attribute value for the calculated attribute UpdatedBy
   */
  public String getUpdatedBy()
  {
    return (String) getAttributeInternal(UPDATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute UpdatedBy
   */
  public void setUpdatedBy(String value)
  {
    setAttributeInternal(UPDATEDBY, value);
  }

  /**Gets the attribute value for the calculated attribute LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date) getAttributeInternal(LASTUPDATEDATE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case IOUID:
      return getIouId();
    case CREATEDBY:
      return getCreatedBy();
    case CREATIONDATE:
      return getCreationDate();
    case UPDATEDBY:
      return getUpdatedBy();
    case LASTUPDATEDATE:
      return getLastUpdateDate();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case IOUID:
      setIouId((Number)value);
      return;
    case CREATEDBY:
      setCreatedBy((String)value);
      return;
    case CREATIONDATE:
      setCreationDate((Date)value);
      return;
    case UPDATEDBY:
      setUpdatedBy((String)value);
      return;
    case LASTUPDATEDATE:
      setLastUpdateDate((Date)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }
}
