package xxfin.oracle.apps.ap.pettycash.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExpenseTypeVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public ExpenseTypeVOImpl() {
    }
}
