package xxfin.oracle.apps.ap.iou.schema.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class iouEODefImpl extends OAEntityDefImpl
{
  /**This is the default constructor (do not remove)
   */
  public iouEODefImpl()
  {
  }
}
