package xxfin.oracle.apps.ap.pettycash.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CodeCombinationVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public CodeCombinationVOImpl() {
    }

    /**Gets the bind variable value for ptycsh_dtl_id
     */
    public String getptycsh_dtl_id() {
        return (String)getNamedWhereClauseParam("ptycsh_dtl_id");
    }

    /**Sets <code>value</code> for bind variable ptycsh_dtl_id
     */
    public void setptycsh_dtl_id(String value) {
        setNamedWhereClauseParam("ptycsh_dtl_id", value);
    }
}
