package xxfin.oracle.apps.ap.pettycash.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;

import xxfin.oracle.apps.ap.pettycash.schema.server.PtCshDtlEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PtCshDtlVORowImpl extends OAViewRowImpl {
    public static final int ROWID1 = 0;
    public static final int PTYCSHDTLID = 1;
    public static final int PTYCSHHDRID = 2;
    public static final int DTLNUM = 3;
    public static final int DTLNUMDESC = 4;
    public static final int DTLNUMACT = 5;
    public static final int REQUESTNUMBER = 6;
    public static final int SEGMENT1GOVDESC = 7;
    public static final int EXPENSETYPE = 8;
    public static final int EXPENSETYPEDESC = 9;
    public static final int DEPARTMENT = 10;
    public static final int DEPARTMENTDESC = 11;
    public static final int ACCOUNTNUM = 12;
    public static final int ACCOUNTDESCRIPTION = 13;
    public static final int CURRENCY = 14;
    public static final int AMOUNT = 15;
    public static final int EXCHANGERATETYPE = 16;
    public static final int EXCHANGERATEDATE = 17;
    public static final int EXCHANGERATE = 18;
    public static final int AMOUNTINOMR = 19;
    public static final int BRIEFNARRATION = 20;
    public static final int BUDGETRESULTS = 21;
    public static final int BUDGETRESULTSDESC = 22;
    public static final int CCID = 23;
    public static final int CONCATENATEDSEGMENTS = 24;
    public static final int UPDIMG = 25;
    public static final int DELIMG = 26;
    public static final int ATTACHROUPD = 27;
    public static final int ATTACHFILE = 28;
    public static final int FILEDESC = 29;
    public static final int DIVPROCESSED = 30;
    public static final int OLDPTYCSHHDRID = 31;
    public static final int OLDPTYCSHDTLID = 32;
    public static final int ELIGIBLESELFLAG = 33;
    public static final int ATTRIBUTECATEGORY = 34;
    public static final int ATTRIBUTE1 = 35;
    public static final int ATTRIBUTE2 = 36;
    public static final int ATTRIBUTE3 = 37;
    public static final int ATTRIBUTE4 = 38;
    public static final int ATTRIBUTE5 = 39;
    public static final int ATTRIBUTE6 = 40;
    public static final int ATTRIBUTE7 = 41;
    public static final int ATTRIBUTE8 = 42;
    public static final int ATTRIBUTE9 = 43;
    public static final int ATTRIBUTE10 = 44;
    public static final int READONLY = 45;
    public static final int CREATEDBYUSERNAME = 46;
    public static final int UPDATEDBYUSERNAME = 47;
    public static final int CREATEDBY = 48;
    public static final int CREATIONDATE = 49;
    public static final int LASTUPDATEDBY = 50;
    public static final int LASTUPDATEDATE = 51;
    public static final int LASTUPDATELOGIN = 52;

    /**This is the default constructor (do not remove)
     */
    public PtCshDtlVORowImpl() {
    }

    /**Gets PtCshDtlEO entity object.
     */
    public PtCshDtlEOImpl getPtCshDtlEO() {
        return (PtCshDtlEOImpl)getEntity(0);
    }

    /**Gets the attribute value for the calculated attribute RowId1
     */
    public RowID getRowId1() {
        return (RowID) getAttributeInternal(ROWID1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RowId1
     */
    public void setRowId1(RowID value) {
        setAttributeInternal(ROWID1, value);
    }

    /**Gets the attribute value for PTYCSH_DTL_ID using the alias name PtycshDtlId
     */
    public Number getPtycshDtlId() {
        return (Number) getAttributeInternal(PTYCSHDTLID);
    }

    /**Sets <code>value</code> as attribute value for PTYCSH_DTL_ID using the alias name PtycshDtlId
     */
    public void setPtycshDtlId(Number value) {
        setAttributeInternal(PTYCSHDTLID, value);
    }

    /**Gets the attribute value for PTYCSH_HDR_ID using the alias name PtycshHdrId
     */
    public Number getPtycshHdrId() {
        return (Number) getAttributeInternal(PTYCSHHDRID);
    }

    /**Sets <code>value</code> as attribute value for PTYCSH_HDR_ID using the alias name PtycshHdrId
     */
    public void setPtycshHdrId(Number value) {
        setAttributeInternal(PTYCSHHDRID, value);
    }

    /**Gets the attribute value for the calculated attribute RequestNumber
     */
    public String getRequestNumber() {
        return (String) getAttributeInternal(REQUESTNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RequestNumber
     */
    public void setRequestNumber(String value) {
        setAttributeInternal(REQUESTNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute Segment1GovDesc
     */
    public String getSegment1GovDesc() {
        return (String) getAttributeInternal(SEGMENT1GOVDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Segment1GovDesc
     */
    public void setSegment1GovDesc(String value) {
        setAttributeInternal(SEGMENT1GOVDESC, value);
    }

    /**Gets the attribute value for EXPENSE_TYPE using the alias name ExpenseType
     */
    public String getExpenseType() {
        return (String) getAttributeInternal(EXPENSETYPE);
    }

    /**Sets <code>value</code> as attribute value for EXPENSE_TYPE using the alias name ExpenseType
     */
    public void setExpenseType(String value) {
        setAttributeInternal(EXPENSETYPE, value);
    }

    /**Gets the attribute value for the calculated attribute ExpenseTypeDesc
     */
    public String getExpenseTypeDesc() {
        return (String) getAttributeInternal(EXPENSETYPEDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ExpenseTypeDesc
     */
    public void setExpenseTypeDesc(String value) {
        setAttributeInternal(EXPENSETYPEDESC, value);
    }

    /**Gets the attribute value for DEPARTMENT using the alias name Department
     */
    public String getDepartment() {
        return (String) getAttributeInternal(DEPARTMENT);
    }

    /**Sets <code>value</code> as attribute value for DEPARTMENT using the alias name Department
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**Gets the attribute value for the calculated attribute DepartmentDesc
     */
    public String getDepartmentDesc() {
        return (String) getAttributeInternal(DEPARTMENTDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DepartmentDesc
     */
    public void setDepartmentDesc(String value) {
        setAttributeInternal(DEPARTMENTDESC, value);
    }

    /**Gets the attribute value for ACCOUNT_NUM using the alias name AccountNum
     */
    public String getAccountNum() {
        return (String) getAttributeInternal(ACCOUNTNUM);
    }

    /**Sets <code>value</code> as attribute value for ACCOUNT_NUM using the alias name AccountNum
     */
    public void setAccountNum(String value) {
        setAttributeInternal(ACCOUNTNUM, value);
    }

    /**Gets the attribute value for ACCOUNT_DESCRIPTION using the alias name AccountDescription
     */
    public String getAccountDescription() {
        return (String) getAttributeInternal(ACCOUNTDESCRIPTION);
    }

    /**Sets <code>value</code> as attribute value for ACCOUNT_DESCRIPTION using the alias name AccountDescription
     */
    public void setAccountDescription(String value) {
        setAttributeInternal(ACCOUNTDESCRIPTION, value);
    }

    /**Gets the attribute value for CURRENCY using the alias name Currency
     */
    public String getCurrency() {
        return (String) getAttributeInternal(CURRENCY);
    }

    /**Sets <code>value</code> as attribute value for CURRENCY using the alias name Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**Gets the attribute value for AMOUNT using the alias name Amount
     */
    public Number getAmount() {
        return (Number) getAttributeInternal(AMOUNT);
    }

    /**Sets <code>value</code> as attribute value for AMOUNT using the alias name Amount
     */
    public void setAmount(Number value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**Gets the attribute value for EXCHANGE_RATE_TYPE using the alias name ExchangeRateType
     */
    public String getExchangeRateType() {
        return (String) getAttributeInternal(EXCHANGERATETYPE);
    }

    /**Sets <code>value</code> as attribute value for EXCHANGE_RATE_TYPE using the alias name ExchangeRateType
     */
    public void setExchangeRateType(String value) {
        setAttributeInternal(EXCHANGERATETYPE, value);
    }

    /**Gets the attribute value for EXCHANGE_RATE_DATE using the alias name ExchangeRateDate
     */
    public Date getExchangeRateDate() {
        return (Date) getAttributeInternal(EXCHANGERATEDATE);
    }

    /**Sets <code>value</code> as attribute value for EXCHANGE_RATE_DATE using the alias name ExchangeRateDate
     */
    public void setExchangeRateDate(Date value) {
        setAttributeInternal(EXCHANGERATEDATE, value);
    }

    /**Gets the attribute value for EXCHANGE_RATE using the alias name ExchangeRate
     */
    public String getExchangeRate() {
        return (String) getAttributeInternal(EXCHANGERATE);
    }

    /**Sets <code>value</code> as attribute value for EXCHANGE_RATE using the alias name ExchangeRate
     */
    public void setExchangeRate(String value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**Gets the attribute value for the calculated attribute AmountInOmr
     */
    public Number getAmountInOmr() {
        return (Number) getAttributeInternal(AMOUNTINOMR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AmountInOmr
     */
    public void setAmountInOmr(Number value) {
        setAttributeInternal(AMOUNTINOMR, value);
    }

    /**Gets the attribute value for BRIEF_NARRATION using the alias name BriefNarration
     */
    public String getBriefNarration() {
        return (String) getAttributeInternal(BRIEFNARRATION);
    }

    /**Sets <code>value</code> as attribute value for BRIEF_NARRATION using the alias name BriefNarration
     */
    public void setBriefNarration(String value) {
        setAttributeInternal(BRIEFNARRATION, value);
    }

    /**Gets the attribute value for BUDGET_RESULTS using the alias name BudgetResults
     */
    public String getBudgetResults() {
        return (String) getAttributeInternal(BUDGETRESULTS);
    }

    /**Sets <code>value</code> as attribute value for BUDGET_RESULTS using the alias name BudgetResults
     */
    public void setBudgetResults(String value) {
        setAttributeInternal(BUDGETRESULTS, value);
    }

    /**Gets the attribute value for CC_ID using the alias name CcId
     */
    public Number getCcId() {
        return (Number) getAttributeInternal(CCID);
    }

    /**Sets <code>value</code> as attribute value for CC_ID using the alias name CcId
     */
    public void setCcId(Number value) {
        setAttributeInternal(CCID, value);
    }

    /**Gets the attribute value for CONCATENATED_SEGMENTS using the alias name ConcatenatedSegments
     */
    public String getConcatenatedSegments() {
        return (String) getAttributeInternal(CONCATENATEDSEGMENTS);
    }

    /**Sets <code>value</code> as attribute value for CONCATENATED_SEGMENTS using the alias name ConcatenatedSegments
     */
    public void setConcatenatedSegments(String value) {
        setAttributeInternal(CONCATENATEDSEGMENTS, value);
    }

    /**Gets the attribute value for the calculated attribute UpdImg
     */
    public String getUpdImg() {
        return (String) getAttributeInternal(UPDIMG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute UpdImg
     */
    public void setUpdImg(String value) {
        setAttributeInternal(UPDIMG, value);
    }

    /**Gets the attribute value for the calculated attribute DelImg
     */
    public String getDelImg() {
        return (String) getAttributeInternal(DELIMG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DelImg
     */
    public void setDelImg(String value) {
        setAttributeInternal(DELIMG, value);
    }

    /**Gets the attribute value for ATTACH_FILE using the alias name AttachFile
     */
    public BlobDomain getAttachFile() {
        return (BlobDomain) getAttributeInternal(ATTACHFILE);
    }

    /**Sets <code>value</code> as attribute value for ATTACH_FILE using the alias name AttachFile
     */
    public void setAttachFile(BlobDomain value) {
        setAttributeInternal(ATTACHFILE, value);
    }

    /**Gets the attribute value for FILE_DESC using the alias name FileDesc
     */
    public String getFileDesc() {
        return (String) getAttributeInternal(FILEDESC);
    }

    /**Sets <code>value</code> as attribute value for FILE_DESC using the alias name FileDesc
     */
    public void setFileDesc(String value) {
        setAttributeInternal(FILEDESC, value);
    }

    /**Gets the attribute value for DIV_PROCESSED using the alias name DivProcessed
     */
    public String getDivProcessed() {
        return (String) getAttributeInternal(DIVPROCESSED);
    }

    /**Sets <code>value</code> as attribute value for DIV_PROCESSED using the alias name DivProcessed
     */
    public void setDivProcessed(String value) {
        setAttributeInternal(DIVPROCESSED, value);
    }

    /**Gets the attribute value for OLD_PTYCSH_HDR_ID using the alias name OldPtycshHdrId
     */
    public Number getOldPtycshHdrId() {
        return (Number) getAttributeInternal(OLDPTYCSHHDRID);
    }

    /**Sets <code>value</code> as attribute value for OLD_PTYCSH_HDR_ID using the alias name OldPtycshHdrId
     */
    public void setOldPtycshHdrId(Number value) {
        setAttributeInternal(OLDPTYCSHHDRID, value);
    }

    /**Gets the attribute value for OLD_PTYCSH_DTL_ID using the alias name OldPtycshDtlId
     */
    public Number getOldPtycshDtlId() {
        return (Number) getAttributeInternal(OLDPTYCSHDTLID);
    }

    /**Sets <code>value</code> as attribute value for OLD_PTYCSH_DTL_ID using the alias name OldPtycshDtlId
     */
    public void setOldPtycshDtlId(Number value) {
        setAttributeInternal(OLDPTYCSHDTLID, value);
    }

    /**Gets the attribute value for ELIGIBLE_SEL_FLAG using the alias name EligibleSelFlag
     */
    public String getEligibleSelFlag() {
        return (String) getAttributeInternal(ELIGIBLESELFLAG);
    }

    /**Sets <code>value</code> as attribute value for ELIGIBLE_SEL_FLAG using the alias name EligibleSelFlag
     */
    public void setEligibleSelFlag(String value) {
        setAttributeInternal(ELIGIBLESELFLAG, value);
    }

    /**Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for the calculated attribute ReadOnly
     */
    public Boolean getReadOnly() {
        return (Boolean) getAttributeInternal(READONLY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReadOnly
     */
    public void setReadOnly(Boolean value) {
        setAttributeInternal(READONLY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROWID1:
            return getRowId1();
        case PTYCSHDTLID:
            return getPtycshDtlId();
        case PTYCSHHDRID:
            return getPtycshHdrId();
        case DTLNUM:
            return getDtlNum();
        case DTLNUMDESC:
            return getDtlNumDesc();
        case DTLNUMACT:
            return getDtlNumAct();
        case REQUESTNUMBER:
            return getRequestNumber();
        case SEGMENT1GOVDESC:
            return getSegment1GovDesc();
        case EXPENSETYPE:
            return getExpenseType();
        case EXPENSETYPEDESC:
            return getExpenseTypeDesc();
        case DEPARTMENT:
            return getDepartment();
        case DEPARTMENTDESC:
            return getDepartmentDesc();
        case ACCOUNTNUM:
            return getAccountNum();
        case ACCOUNTDESCRIPTION:
            return getAccountDescription();
        case CURRENCY:
            return getCurrency();
        case AMOUNT:
            return getAmount();
        case EXCHANGERATETYPE:
            return getExchangeRateType();
        case EXCHANGERATEDATE:
            return getExchangeRateDate();
        case EXCHANGERATE:
            return getExchangeRate();
        case AMOUNTINOMR:
            return getAmountInOmr();
        case BRIEFNARRATION:
            return getBriefNarration();
        case BUDGETRESULTS:
            return getBudgetResults();
        case BUDGETRESULTSDESC:
            return getBudgetResultsDesc();
        case CCID:
            return getCcId();
        case CONCATENATEDSEGMENTS:
            return getConcatenatedSegments();
        case UPDIMG:
            return getUpdImg();
        case DELIMG:
            return getDelImg();
        case ATTACHROUPD:
            return getAttachRoUpd();
        case ATTACHFILE:
            return getAttachFile();
        case FILEDESC:
            return getFileDesc();
        case DIVPROCESSED:
            return getDivProcessed();
        case OLDPTYCSHHDRID:
            return getOldPtycshHdrId();
        case OLDPTYCSHDTLID:
            return getOldPtycshDtlId();
        case ELIGIBLESELFLAG:
            return getEligibleSelFlag();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE8:
            return getAttribute8();
        case ATTRIBUTE9:
            return getAttribute9();
        case ATTRIBUTE10:
            return getAttribute10();
        case READONLY:
            return getReadOnly();
        case CREATEDBYUSERNAME:
            return getCreatedByUsername();
        case UPDATEDBYUSERNAME:
            return getUpdatedByUsername();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROWID1:
            setRowId1((RowID)value);
            return;
        case PTYCSHDTLID:
            setPtycshDtlId((Number)value);
            return;
        case PTYCSHHDRID:
            setPtycshHdrId((Number)value);
            return;
        case DTLNUM:
            setDtlNum((String)value);
            return;
        case DTLNUMDESC:
            setDtlNumDesc((String)value);
            return;
        case DTLNUMACT:
            setDtlNumAct((String)value);
            return;
        case REQUESTNUMBER:
            setRequestNumber((String)value);
            return;
        case SEGMENT1GOVDESC:
            setSegment1GovDesc((String)value);
            return;
        case EXPENSETYPE:
            setExpenseType((String)value);
            return;
        case EXPENSETYPEDESC:
            setExpenseTypeDesc((String)value);
            return;
        case DEPARTMENT:
            setDepartment((String)value);
            return;
        case DEPARTMENTDESC:
            setDepartmentDesc((String)value);
            return;
        case ACCOUNTNUM:
            setAccountNum((String)value);
            return;
        case ACCOUNTDESCRIPTION:
            setAccountDescription((String)value);
            return;
        case CURRENCY:
            setCurrency((String)value);
            return;
        case AMOUNT:
            setAmount((Number)value);
            return;
        case EXCHANGERATETYPE:
            setExchangeRateType((String)value);
            return;
        case EXCHANGERATEDATE:
            setExchangeRateDate((Date)value);
            return;
        case EXCHANGERATE:
            setExchangeRate((String)value);
            return;
        case AMOUNTINOMR:
            setAmountInOmr((Number)value);
            return;
        case BRIEFNARRATION:
            setBriefNarration((String)value);
            return;
        case BUDGETRESULTS:
            setBudgetResults((String)value);
            return;
        case BUDGETRESULTSDESC:
            setBudgetResultsDesc((String)value);
            return;
        case CCID:
            setCcId((Number)value);
            return;
        case CONCATENATEDSEGMENTS:
            setConcatenatedSegments((String)value);
            return;
        case UPDIMG:
            setUpdImg((String)value);
            return;
        case DELIMG:
            setDelImg((String)value);
            return;
        case ATTACHROUPD:
            setAttachRoUpd((String)value);
            return;
        case ATTACHFILE:
            setAttachFile((BlobDomain)value);
            return;
        case FILEDESC:
            setFileDesc((String)value);
            return;
        case DIVPROCESSED:
            setDivProcessed((String)value);
            return;
        case OLDPTYCSHHDRID:
            setOldPtycshHdrId((Number)value);
            return;
        case OLDPTYCSHDTLID:
            setOldPtycshDtlId((Number)value);
            return;
        case ELIGIBLESELFLAG:
            setEligibleSelFlag((String)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case ATTRIBUTE6:
            setAttribute6((String)value);
            return;
        case ATTRIBUTE7:
            setAttribute7((String)value);
            return;
        case ATTRIBUTE8:
            setAttribute8((String)value);
            return;
        case ATTRIBUTE9:
            setAttribute9((String)value);
            return;
        case ATTRIBUTE10:
            setAttribute10((String)value);
            return;
        case READONLY:
            setReadOnly((Boolean)value);
            return;
        case CREATEDBYUSERNAME:
            setCreatedByUsername((String)value);
            return;
        case UPDATEDBYUSERNAME:
            setUpdatedByUsername((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute CreatedByUsername
     */
    public String getCreatedByUsername() {
        return (String) getAttributeInternal(CREATEDBYUSERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedByUsername
     */
    public void setCreatedByUsername(String value) {
        setAttributeInternal(CREATEDBYUSERNAME, value);
    }

    /**Gets the attribute value for the calculated attribute UpdatedByUsername
     */
    public String getUpdatedByUsername() {
        return (String) getAttributeInternal(UPDATEDBYUSERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute UpdatedByUsername
     */
    public void setUpdatedByUsername(String value) {
        setAttributeInternal(UPDATEDBYUSERNAME, value);
    }

    /**Gets the attribute value for the calculated attribute BudgetResultsDesc
     */
    public String getBudgetResultsDesc() {
        return (String) getAttributeInternal(BUDGETRESULTSDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BudgetResultsDesc
     */
    public void setBudgetResultsDesc(String value) {
        setAttributeInternal(BUDGETRESULTSDESC, value);
    }

    /**Gets the attribute value for the calculated attribute DtlNum
     */
    public String getDtlNum() {
        return (String) getAttributeInternal(DTLNUM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DtlNum
     */
    public void setDtlNum(String value) {
        setAttributeInternal(DTLNUM, value);
    }

    /**Gets the attribute value for the calculated attribute DtlNumDesc
     */
    public String getDtlNumDesc() {
        return (String) getAttributeInternal(DTLNUMDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DtlNumDesc
     */
    public void setDtlNumDesc(String value) {
        setAttributeInternal(DTLNUMDESC, value);
    }

    /**Gets the attribute value for the calculated attribute DtlNumAct
     */
    public String getDtlNumAct() {
        return (String) getAttributeInternal(DTLNUMACT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DtlNumAct
     */
    public void setDtlNumAct(String value) {
        setAttributeInternal(DTLNUMACT, value);
    }

    /**Gets the attribute value for the calculated attribute AttachRoUpd
     */
    public String getAttachRoUpd() {
        return (String) getAttributeInternal(ATTACHROUPD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AttachRoUpd
     */
    public void setAttachRoUpd(String value) {
        setAttributeInternal(ATTACHROUPD, value);
    }
}
