package xxfin.oracle.apps.ap.pettycash.schema.server;

import oracle.apps.fnd.framework.server.OADBTransaction;
import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PtCshSeqEOImpl extends OAEntityImpl {
    public static final int PTYCSHSEQID = 0;
    public static final int DIVISIONNAME = 1;
    public static final int SEQPREFIX = 2;
    public static final int STARTINGNUMBER = 3;
    public static final int DATESTART = 4;
    public static final int DATEEND = 5;
    public static final int CURRENTRUNNINGSEQUENCE = 6;
    public static final int ATTRIBUTECATEGORY = 7;
    public static final int ATTRIBUTE1 = 8;
    public static final int ATTRIBUTE2 = 9;
    public static final int ATTRIBUTE3 = 10;
    public static final int ATTRIBUTE4 = 11;
    public static final int ATTRIBUTE5 = 12;
    public static final int ATTRIBUTE6 = 13;
    public static final int ATTRIBUTE7 = 14;
    public static final int ATTRIBUTE8 = 15;
    public static final int ATTRIBUTE9 = 16;
    public static final int ATTRIBUTE10 = 17;
    public static final int CREATEDBY = 18;
    public static final int CREATIONDATE = 19;
    public static final int LASTUPDATEDBY = 20;
    public static final int LASTUPDATEDATE = 21;
    public static final int LASTUPDATELOGIN = 22;
    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public PtCshSeqEOImpl() {
    }

    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxfin.oracle.apps.ap.pettycash.schema.server.PtCshSeqEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
        OADBTransaction transaction = getOADBTransaction();
        Number ptCashSeqId = transaction.getSequenceValue("XXFIN_AP_PETTYCASH_SEQ_S");
        System.out.println("Inside Create in EO value of  param "+ptCashSeqId);
        setPtycshSeqId(ptCashSeqId);
//        setStartingNumber(0);
        setPtycshSeqId(ptCashSeqId);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }

    /**Gets the attribute value for PtycshSeqId, using the alias name PtycshSeqId
     */
    public Number getPtycshSeqId() {
        return (Number)getAttributeInternal(PTYCSHSEQID);
    }

    /**Sets <code>value</code> as the attribute value for PtycshSeqId
     */
    public void setPtycshSeqId(Number value) {
        setAttributeInternal(PTYCSHSEQID, value);
    }

    /**Gets the attribute value for DivisionName, using the alias name DivisionName
     */
    public String getDivisionName() {
        return (String)getAttributeInternal(DIVISIONNAME);
    }

    /**Sets <code>value</code> as the attribute value for DivisionName
     */
    public void setDivisionName(String value) {
        setAttributeInternal(DIVISIONNAME, value);
    }

    /**Gets the attribute value for SeqPrefix, using the alias name SeqPrefix
     */
    public String getSeqPrefix() {
        return (String)getAttributeInternal(SEQPREFIX);
    }

    /**Sets <code>value</code> as the attribute value for SeqPrefix
     */
    public void setSeqPrefix(String value) {
        setAttributeInternal(SEQPREFIX, value);
    }

    /**Gets the attribute value for StartingNumber, using the alias name StartingNumber
     */
    public Number getStartingNumber() {
        return (Number)getAttributeInternal(STARTINGNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for StartingNumber
     */
    public void setStartingNumber(Number value) {
        setAttributeInternal(STARTINGNUMBER, value);
    }

    /**Gets the attribute value for DateStart, using the alias name DateStart
     */
    public Date getDateStart() {
        return (Date)getAttributeInternal(DATESTART);
    }

    /**Sets <code>value</code> as the attribute value for DateStart
     */
    public void setDateStart(Date value) {
        setAttributeInternal(DATESTART, value);
    }

    /**Gets the attribute value for DateEnd, using the alias name DateEnd
     */
    public Date getDateEnd() {
        return (Date)getAttributeInternal(DATEEND);
    }

    /**Sets <code>value</code> as the attribute value for DateEnd
     */
    public void setDateEnd(Date value) {
        setAttributeInternal(DATEEND, value);
    }

    /**Gets the attribute value for CurrentRunningSequence, using the alias name CurrentRunningSequence
     */
    public Number getCurrentRunningSequence() {
        return (Number)getAttributeInternal(CURRENTRUNNINGSEQUENCE);
    }

    /**Sets <code>value</code> as the attribute value for CurrentRunningSequence
     */
    public void setCurrentRunningSequence(Number value) {
        setAttributeInternal(CURRENTRUNNINGSEQUENCE, value);
    }

    /**Gets the attribute value for AttributeCategory, using the alias name AttributeCategory
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for Attribute1, using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for Attribute2, using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for Attribute3, using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for Attribute4, using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for Attribute5, using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for Attribute6, using the alias name Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**Sets <code>value</code> as the attribute value for Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**Gets the attribute value for Attribute7, using the alias name Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**Sets <code>value</code> as the attribute value for Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**Gets the attribute value for Attribute8, using the alias name Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**Sets <code>value</code> as the attribute value for Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**Gets the attribute value for Attribute9, using the alias name Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as the attribute value for Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for Attribute10, using the alias name Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**Sets <code>value</code> as the attribute value for Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PTYCSHSEQID:
            return getPtycshSeqId();
        case DIVISIONNAME:
            return getDivisionName();
        case SEQPREFIX:
            return getSeqPrefix();
        case STARTINGNUMBER:
            return getStartingNumber();
        case DATESTART:
            return getDateStart();
        case DATEEND:
            return getDateEnd();
        case CURRENTRUNNINGSEQUENCE:
            return getCurrentRunningSequence();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE8:
            return getAttribute8();
        case ATTRIBUTE9:
            return getAttribute9();
        case ATTRIBUTE10:
            return getAttribute10();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PTYCSHSEQID:
            setPtycshSeqId((Number)value);
            return;
        case DIVISIONNAME:
            setDivisionName((String)value);
            return;
        case SEQPREFIX:
            setSeqPrefix((String)value);
            return;
        case STARTINGNUMBER:
            setStartingNumber((Number)value);
            return;
        case DATESTART:
            setDateStart((Date)value);
            return;
        case DATEEND:
            setDateEnd((Date)value);
            return;
        case CURRENTRUNNINGSEQUENCE:
            setCurrentRunningSequence((Number)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case ATTRIBUTE6:
            setAttribute6((String)value);
            return;
        case ATTRIBUTE7:
            setAttribute7((String)value);
            return;
        case ATTRIBUTE8:
            setAttribute8((String)value);
            return;
        case ATTRIBUTE9:
            setAttribute9((String)value);
            return;
        case ATTRIBUTE10:
            setAttribute10((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number ptycshSeqId) {
        return new Key(new Object[]{ptycshSeqId});
    }
}
