package xxfin.oracle.apps.ap.iou.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class iouEmpLOVVORowImpl extends OAViewRowImpl
{
  public static final int PERSONID = 0;
  public static final int EMPLOYEENUMBER = 1;
  public static final int FULLNAME = 2;
  public static final int EMAILADDRESS = 3;

  /**This is the default constructor (do not remove)
   */
  public iouEmpLOVVORowImpl()
  {
  }

  /**Gets the attribute value for the calculated attribute PersonId
   */
  public Number getPersonId()
  {
    return (Number) getAttributeInternal(PERSONID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PersonId
   */
  public void setPersonId(Number value)
  {
    setAttributeInternal(PERSONID, value);
  }

  /**Gets the attribute value for the calculated attribute EmployeeNumber
   */
  public String getEmployeeNumber()
  {
    return (String) getAttributeInternal(EMPLOYEENUMBER);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute EmployeeNumber
   */
  public void setEmployeeNumber(String value)
  {
    setAttributeInternal(EMPLOYEENUMBER, value);
  }

  /**Gets the attribute value for the calculated attribute FullName
   */
  public String getFullName()
  {
    return (String) getAttributeInternal(FULLNAME);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute FullName
   */
  public void setFullName(String value)
  {
    setAttributeInternal(FULLNAME, value);
  }

  /**Gets the attribute value for the calculated attribute EmailAddress
   */
  public String getEmailAddress()
  {
    return (String) getAttributeInternal(EMAILADDRESS);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute EmailAddress
   */
  public void setEmailAddress(String value)
  {
    setAttributeInternal(EMAILADDRESS, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case PERSONID:
      return getPersonId();
    case EMPLOYEENUMBER:
      return getEmployeeNumber();
    case FULLNAME:
      return getFullName();
    case EMAILADDRESS:
      return getEmailAddress();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case PERSONID:
      setPersonId((Number)value);
      return;
    case EMPLOYEENUMBER:
      setEmployeeNumber((String)value);
      return;
    case FULLNAME:
      setFullName((String)value);
      return;
    case EMAILADDRESS:
      setEmailAddress((String)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }
}
